export const allowedExtensions: Record<string, string> = {
  jpg: "image/jpeg",
  jpeg: "image/jpeg",
  png: "image/png",
  gif: "image/gif",
  svg: "image/svg+xml",
  webp: "image/webp",
  bmp: "image/bmp",
  ico: "image/x-icon",
  pdf: "application/pdf",
  doc: "application/msword",
  docx: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  xls: "application/vnd.ms-excel",
  xlsx: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  ppt: "application/vnd.ms-powerpoint",
  pptx: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  mp3: "audio/mp3",
  wav: "audio/wav",
  txt: "text/plain",
  html: "text/html",
  htm: "text/html",
  css: "text/css",
  md: "text/markdown",
  js: "application/javascript",
  json: "application/json",
  xml: "application/xml",
  zip: "application/zip",
  rar: "application/x-rar-compressed",
  "7z": "application/x-7z-compressed",
  tar: "application/x-tar",
  gz: "application/gzip",
  mp4: "video/mp4",
  mpeg: "video/mpeg",
  ogg: "video/ogg",
  webm: "video/webm",
  yaml: "application/yaml",
  yml: "application/yaml",
  py: "text/x-python",
  ts: "application/typescript",
  jsx: "text/jsx",
  tsx: "text/tsx",
  vue: "text/plain",
  java: "text/x-java",
  cpp: "text/x-c",
  c: "text/x-c",
  sh: "text/x-shellscript",
  php: "text/x-php",
  go: "text/x-go",
  rs: "text/x-rust",
  rb: "text/x-ruby",
  sql: "text/x-sql",
  csv: "text/csv",
  toml: "text/plain",
  env: "text/plain",
  ini: "text/plain",
  // Executables & binary installers
  exe: "application/x-msdownload",
  msi: "application/x-msi",
  dmg: "application/x-apple-diskimage",
  pkg: "application/x-newton-compatible-pkg",
  deb: "application/vnd.debian.binary-package",
  rpm: "application/x-rpm",
  bin: "application/octet-stream",
  iso: "application/x-iso9660-image",
  apk: "application/vnd.android.package-archive",
  appimage: "application/x-executable",
};

export const validTextFiles = {
  txt: "text/plain",
  html: "text/html",
  htm: "text/html",
  md: "text/markdown",
  json: "application/json",
  css: "text/css",
  js: "text/javascript",
  ts: "application/typescript",
  py: "text/x-python",
  csv: "text/csv",
  sql: "text/x-sql",
  sh: "text/x-shellscript",
  xml: "application/xml",
  yaml: "application/yaml",
  yml: "application/yaml",
  env: "text/plain",
  toml: "text/plain",
  ini: "text/plain",
};

export const fileTypes: Record<string, string> = {
  folder: "folder",
  // image
  "image/png": "image",
  "image/jpeg": "image",
  "image/gif": "image",
  "image/svg+xml": "image",
  "image/webp": "image",
  "image/jpg": "image",
  "image/bmp": "image",
  // video
  "video/mp4": "video",
  "video/mpeg": "video",
  "video/ogg": "video",
  "video/webm": "video",
  // audio
  "audio/mp3": "audio",
  // text
  "text/plain": "text",
  "text/html": "html",
  "text/markdown": "markdown",
  "text/csv": "csv",
  "text/css": "css",
  "text/javascript": "js",
  // data
  "application/json": "json",
  "application/xml": "xml",
  // document
  "application/pdf": "pdf",
  "application/msword": "word",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document": "word",
  "application/vnd.ms-excel": "excel",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": "excel",
  "application/vnd.ms-powerpoint": "powerpoint",
  "application/vnd.openxmlformats-officedocument.presentationml.presentation": "powerpoint",
  "application/zip": "archive",
  "application/x-zip-compressed": "archive",
  "application/x-rar-compressed": "archive",
  "application/x-7z-compressed": "archive",
  "application/x-tar": "archive",
  "application/gzip": "archive",
  "application/x-sqlite3": "sqlite",
  "application/yaml": "yaml",
  // Executables & binary installers
  "application/x-msdownload": "executable",
  "application/x-msdos-program": "executable",
  "application/x-msi": "executable",
  "application/x-apple-diskimage": "executable",
  "application/x-newton-compatible-pkg": "executable",
  "application/vnd.debian.binary-package": "executable",
  "application/x-rpm": "executable",
  "application/x-iso9660-image": "executable",
  "application/vnd.android.package-archive": "executable",
  "application/x-executable": "executable",
  "application/octet-stream": "binary",
};
export const fileIcons = {
  folder: "lucide:folder",
  image: "vscode-icons:file-type-image",
  video: "vscode-icons:file-type-video",
  audio: "vscode-icons:file-type-audio",
  pdf: "vscode-icons:file-type-pdf2",
  word: "vscode-icons:file-type-word",
  excel: "vscode-icons:file-type-excel",
  powerpoint: "vscode-icons:file-type-powerpoint",
  html: "vscode-icons:file-type-html",
  css: "vscode-icons:file-type-css",
  js: "vscode-icons:file-type-js-official",
  ts: "vscode-icons:file-type-typescript-official",
  archive: "vscode-icons:file-type-zip",
  text: "vscode-icons:file-type-text",
  markdown: "vscode-icons:file-type-markdown",
  json: "vscode-icons:file-type-json",
  xml: "vscode-icons:file-type-xml",
  csv: "vscode-icons:file-type-db",
  sqlite: "vscode-icons:file-type-sqlite",
  yaml: "vscode-icons:file-type-yaml",
  executable: "vscode-icons:file-type-binary",
  binary: "vscode-icons:default-file",
  default: "vscode-icons:default-file",
};

export const memberRoles = [
  {
    value: "viewer",
    label: "Viewer",
    icon: "lucide:eye",
  },
  {
    value: "editor",
    label: "Editor",
    icon: "lucide:pencil",
  },
  {
    value: "none",
    label: "None",
    icon: "lucide:ban",
  },
];

export const visibilityOptions = [
  {
    value: "public",
    label: "Public",
    icon: "lucide:earth",
  },
  {
    value: "private",
    label: "Private",
    icon: "lucide:lock",
  },
  {
    value: "inherit",
    label: "Inherit",
    icon: "lucide:folder",
  },
];
